# Generated by Django 4.2.4 on 2023-11-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('depart_time', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=50)),
            ],
        ),
    ]
